name: disp
description: An extremely basic Lisp interpreter written in Dart.
version: 1.0.0
homepage: https://github.com/glesica/disp
author: George Lesica <george@lesica.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  args: ^1.5.1
  build: ^1.0.0
  code_builder: ^3.1.0
  path: ^1.4.0
  petitparser: ^2.1.0

dev_dependencies:
  build_runner: ^1.0.0
  test: ^1.0.0
